/** Initial airport catalog — idempotently upserted on first start. Admins can edit, add, or deactivate in the UI. */

export interface AirportSeed {
  iata: string;
  icao?: string;
  name: string;
  city: string;
  region?: string;
  country: string;
  countryCode: string;
}

export const AIRPORT_SEED: AirportSeed[] = [
  // ---------------- United States ----------------
  { iata: "ATL", icao: "KATL", name: "Hartsfield–Jackson Atlanta International", city: "Atlanta", region: "Georgia", country: "United States", countryCode: "US" },
  { iata: "DFW", icao: "KDFW", name: "Dallas/Fort Worth International", city: "Dallas", region: "Texas", country: "United States", countryCode: "US" },
  { iata: "DEN", icao: "KDEN", name: "Denver International", city: "Denver", region: "Colorado", country: "United States", countryCode: "US" },
  { iata: "LAX", icao: "KLAX", name: "Los Angeles International", city: "Los Angeles", region: "California", country: "United States", countryCode: "US" },
  { iata: "ORD", icao: "KORD", name: "Chicago O'Hare International", city: "Chicago", region: "Illinois", country: "United States", countryCode: "US" },
  { iata: "JFK", icao: "KJFK", name: "John F. Kennedy International", city: "New York", region: "New York", country: "United States", countryCode: "US" },
  { iata: "LGA", icao: "KLGA", name: "LaGuardia", city: "New York", region: "New York", country: "United States", countryCode: "US" },
  { iata: "EWR", icao: "KEWR", name: "Newark Liberty International", city: "Newark", region: "New Jersey", country: "United States", countryCode: "US" },
  { iata: "MCO", icao: "KMCO", name: "Orlando International", city: "Orlando", region: "Florida", country: "United States", countryCode: "US" },
  { iata: "MIA", icao: "KMIA", name: "Miami International", city: "Miami", region: "Florida", country: "United States", countryCode: "US" },
  { iata: "FLL", icao: "KFLL", name: "Fort Lauderdale–Hollywood International", city: "Fort Lauderdale", region: "Florida", country: "United States", countryCode: "US" },
  { iata: "TPA", icao: "KTPA", name: "Tampa International", city: "Tampa", region: "Florida", country: "United States", countryCode: "US" },
  { iata: "JAX", icao: "KJAX", name: "Jacksonville International", city: "Jacksonville", region: "Florida", country: "United States", countryCode: "US" },
  { iata: "PBI", icao: "KPBI", name: "Palm Beach International", city: "West Palm Beach", region: "Florida", country: "United States", countryCode: "US" },
  { iata: "RSW", icao: "KRSW", name: "Southwest Florida International", city: "Fort Myers", region: "Florida", country: "United States", countryCode: "US" },
  { iata: "SFO", icao: "KSFO", name: "San Francisco International", city: "San Francisco", region: "California", country: "United States", countryCode: "US" },
  { iata: "OAK", icao: "KOAK", name: "Oakland International", city: "Oakland", region: "California", country: "United States", countryCode: "US" },
  { iata: "SJC", icao: "KSJC", name: "San Jose International", city: "San Jose", region: "California", country: "United States", countryCode: "US" },
  { iata: "SAN", icao: "KSAN", name: "San Diego International", city: "San Diego", region: "California", country: "United States", countryCode: "US" },
  { iata: "SEA", icao: "KSEA", name: "Seattle–Tacoma International", city: "Seattle", region: "Washington", country: "United States", countryCode: "US" },
  { iata: "PDX", icao: "KPDX", name: "Portland International", city: "Portland", region: "Oregon", country: "United States", countryCode: "US" },
  { iata: "PHX", icao: "KPHX", name: "Phoenix Sky Harbor International", city: "Phoenix", region: "Arizona", country: "United States", countryCode: "US" },
  { iata: "LAS", icao: "KLAS", name: "Harry Reid International", city: "Las Vegas", region: "Nevada", country: "United States", countryCode: "US" },
  { iata: "RNO", icao: "KRNO", name: "Reno–Tahoe International", city: "Reno", region: "Nevada", country: "United States", countryCode: "US" },
  { iata: "SLC", icao: "KSLC", name: "Salt Lake City International", city: "Salt Lake City", region: "Utah", country: "United States", countryCode: "US" },
  { iata: "MSP", icao: "KMSP", name: "Minneapolis–Saint Paul International", city: "Minneapolis", region: "Minnesota", country: "United States", countryCode: "US" },
  { iata: "DTW", icao: "KDTW", name: "Detroit Metropolitan Wayne County", city: "Detroit", region: "Michigan", country: "United States", countryCode: "US" },
  { iata: "CLE", icao: "KCLE", name: "Cleveland Hopkins International", city: "Cleveland", region: "Ohio", country: "United States", countryCode: "US" },
  { iata: "CMH", icao: "KCMH", name: "John Glenn Columbus International", city: "Columbus", region: "Ohio", country: "United States", countryCode: "US" },
  { iata: "CVG", icao: "KCVG", name: "Cincinnati/Northern Kentucky International", city: "Cincinnati", region: "Kentucky", country: "United States", countryCode: "US" },
  { iata: "IND", icao: "KIND", name: "Indianapolis International", city: "Indianapolis", region: "Indiana", country: "United States", countryCode: "US" },
  { iata: "PIT", icao: "KPIT", name: "Pittsburgh International", city: "Pittsburgh", region: "Pennsylvania", country: "United States", countryCode: "US" },
  { iata: "PHL", icao: "KPHL", name: "Philadelphia International", city: "Philadelphia", region: "Pennsylvania", country: "United States", countryCode: "US" },
  { iata: "BWI", icao: "KBWI", name: "Baltimore/Washington International Thurgood Marshall", city: "Baltimore", region: "Maryland", country: "United States", countryCode: "US" },
  { iata: "DCA", icao: "KDCA", name: "Ronald Reagan Washington National", city: "Washington", region: "District of Columbia", country: "United States", countryCode: "US" },
  { iata: "IAD", icao: "KIAD", name: "Washington Dulles International", city: "Washington", region: "District of Columbia", country: "United States", countryCode: "US" },
  { iata: "BOS", icao: "KBOS", name: "Boston Logan International", city: "Boston", region: "Massachusetts", country: "United States", countryCode: "US" },
  { iata: "PVD", icao: "KPVD", name: "Rhode Island T.F. Green International", city: "Providence", region: "Rhode Island", country: "United States", countryCode: "US" },
  { iata: "BDL", icao: "KBDL", name: "Bradley International", city: "Hartford", region: "Connecticut", country: "United States", countryCode: "US" },
  { iata: "BUF", icao: "KBUF", name: "Buffalo Niagara International", city: "Buffalo", region: "New York", country: "United States", countryCode: "US" },
  { iata: "ROC", icao: "KROC", name: "Greater Rochester International", city: "Rochester", region: "New York", country: "United States", countryCode: "US" },
  { iata: "SYR", icao: "KSYR", name: "Syracuse Hancock International", city: "Syracuse", region: "New York", country: "United States", countryCode: "US" },
  { iata: "ALB", icao: "KALB", name: "Albany International", city: "Albany", region: "New York", country: "United States", countryCode: "US" },
  { iata: "BNA", icao: "KBNA", name: "Nashville International", city: "Nashville", region: "Tennessee", country: "United States", countryCode: "US" },
  { iata: "MEM", icao: "KMEM", name: "Memphis International", city: "Memphis", region: "Tennessee", country: "United States", countryCode: "US" },
  { iata: "CHA", icao: "KCHA", name: "Chattanooga Metropolitan", city: "Chattanooga", region: "Tennessee", country: "United States", countryCode: "US" },
  { iata: "CLT", icao: "KCLT", name: "Charlotte Douglas International", city: "Charlotte", region: "North Carolina", country: "United States", countryCode: "US" },
  { iata: "RDU", icao: "KRDU", name: "Raleigh–Durham International", city: "Raleigh", region: "North Carolina", country: "United States", countryCode: "US" },
  { iata: "GSO", icao: "KGSO", name: "Piedmont Triad International", city: "Greensboro", region: "North Carolina", country: "United States", countryCode: "US" },
  { iata: "CHS", icao: "KCHS", name: "Charleston International", city: "Charleston", region: "South Carolina", country: "United States", countryCode: "US" },
  { iata: "CAE", icao: "KCAE", name: "Columbia Metropolitan", city: "Columbia", region: "South Carolina", country: "United States", countryCode: "US" },
  { iata: "SAV", icao: "KSAV", name: "Savannah/Hilton Head International", city: "Savannah", region: "Georgia", country: "United States", countryCode: "US" },
  { iata: "MSY", icao: "KMSY", name: "Louis Armstrong New Orleans International", city: "New Orleans", region: "Louisiana", country: "United States", countryCode: "US" },
  { iata: "BHM", icao: "KBHM", name: "Birmingham–Shuttlesworth International", city: "Birmingham", region: "Alabama", country: "United States", countryCode: "US" },
  { iata: "HSV", icao: "KHSV", name: "Huntsville International", city: "Huntsville", region: "Alabama", country: "United States", countryCode: "US" },
  { iata: "JAN", icao: "KJAN", name: "Jackson–Medgar Wiley Evers International", city: "Jackson", region: "Mississippi", country: "United States", countryCode: "US" },
  { iata: "LIT", icao: "KLIT", name: "Bill and Hillary Clinton National", city: "Little Rock", region: "Arkansas", country: "United States", countryCode: "US" },
  { iata: "IAH", icao: "KIAH", name: "George Bush Intercontinental", city: "Houston", region: "Texas", country: "United States", countryCode: "US" },
  { iata: "HOU", icao: "KHOU", name: "William P. Hobby", city: "Houston", region: "Texas", country: "United States", countryCode: "US" },
  { iata: "AUS", icao: "KAUS", name: "Austin–Bergstrom International", city: "Austin", region: "Texas", country: "United States", countryCode: "US" },
  { iata: "SAT", icao: "KSAT", name: "San Antonio International", city: "San Antonio", region: "Texas", country: "United States", countryCode: "US" },
  { iata: "ELP", icao: "KELP", name: "El Paso International", city: "El Paso", region: "Texas", country: "United States", countryCode: "US" },
  { iata: "OKC", icao: "KOKC", name: "Will Rogers World", city: "Oklahoma City", region: "Oklahoma", country: "United States", countryCode: "US" },
  { iata: "TUL", icao: "KTUL", name: "Tulsa International", city: "Tulsa", region: "Oklahoma", country: "United States", countryCode: "US" },
  { iata: "MCI", icao: "KMCI", name: "Kansas City International", city: "Kansas City", region: "Missouri", country: "United States", countryCode: "US" },
  { iata: "STL", icao: "KSTL", name: "St. Louis Lambert International", city: "St. Louis", region: "Missouri", country: "United States", countryCode: "US" },
  { iata: "OMA", icao: "KOMA", name: "Eppley Airfield", city: "Omaha", region: "Nebraska", country: "United States", countryCode: "US" },
  { iata: "DSM", icao: "KDSM", name: "Des Moines International", city: "Des Moines", region: "Iowa", country: "United States", countryCode: "US" },
  { iata: "MKE", icao: "KMKE", name: "Milwaukee Mitchell International", city: "Milwaukee", region: "Wisconsin", country: "United States", countryCode: "US" },
  { iata: "MDW", icao: "KMDW", name: "Chicago Midway International", city: "Chicago", region: "Illinois", country: "United States", countryCode: "US" },
  { iata: "BOI", icao: "KBOI", name: "Boise Airport", city: "Boise", region: "Idaho", country: "United States", countryCode: "US" },
  { iata: "BZN", icao: "KBZN", name: "Bozeman Yellowstone International", city: "Bozeman", region: "Montana", country: "United States", countryCode: "US" },
  { iata: "JAC", icao: "KJAC", name: "Jackson Hole", city: "Jackson", region: "Wyoming", country: "United States", countryCode: "US" },
  { iata: "ASE", icao: "KASE", name: "Aspen/Pitkin County", city: "Aspen", region: "Colorado", country: "United States", countryCode: "US" },
  { iata: "EGE", icao: "KEGE", name: "Eagle County Regional", city: "Vail", region: "Colorado", country: "United States", countryCode: "US" },
  { iata: "COS", icao: "KCOS", name: "Colorado Springs Airport", city: "Colorado Springs", region: "Colorado", country: "United States", countryCode: "US" },
  { iata: "ABQ", icao: "KABQ", name: "Albuquerque International Sunport", city: "Albuquerque", region: "New Mexico", country: "United States", countryCode: "US" },
  { iata: "TUS", icao: "KTUS", name: "Tucson International", city: "Tucson", region: "Arizona", country: "United States", countryCode: "US" },
  { iata: "BUR", icao: "KBUR", name: "Hollywood Burbank", city: "Burbank", region: "California", country: "United States", countryCode: "US" },
  { iata: "ONT", icao: "KONT", name: "Ontario International", city: "Ontario", region: "California", country: "United States", countryCode: "US" },
  { iata: "SNA", icao: "KSNA", name: "John Wayne", city: "Santa Ana", region: "California", country: "United States", countryCode: "US" },
  { iata: "LGB", icao: "KLGB", name: "Long Beach", city: "Long Beach", region: "California", country: "United States", countryCode: "US" },
  { iata: "SBA", icao: "KSBA", name: "Santa Barbara Airport", city: "Santa Barbara", region: "California", country: "United States", countryCode: "US" },
  { iata: "FAT", icao: "KFAT", name: "Fresno Yosemite International", city: "Fresno", region: "California", country: "United States", countryCode: "US" },
  { iata: "MRY", icao: "KMRY", name: "Monterey Regional", city: "Monterey", region: "California", country: "United States", countryCode: "US" },
  { iata: "HNL", icao: "PHNL", name: "Daniel K. Inouye International", city: "Honolulu", region: "Hawaii", country: "United States", countryCode: "US" },
  { iata: "OGG", icao: "PHOG", name: "Kahului", city: "Kahului", region: "Hawaii", country: "United States", countryCode: "US" },
  { iata: "KOA", icao: "PHKO", name: "Ellison Onizuka Kona International", city: "Kailua-Kona", region: "Hawaii", country: "United States", countryCode: "US" },
  { iata: "LIH", icao: "PHLI", name: "Lihue Airport", city: "Lihue", region: "Hawaii", country: "United States", countryCode: "US" },
  { iata: "ITO", icao: "PHTO", name: "Hilo International", city: "Hilo", region: "Hawaii", country: "United States", countryCode: "US" },
  { iata: "ANC", icao: "PANC", name: "Ted Stevens Anchorage International", city: "Anchorage", region: "Alaska", country: "United States", countryCode: "US" },
  { iata: "FAI", icao: "PAFA", name: "Fairbanks International", city: "Fairbanks", region: "Alaska", country: "United States", countryCode: "US" },
  { iata: "JNU", icao: "PAJN", name: "Juneau International", city: "Juneau", region: "Alaska", country: "United States", countryCode: "US" },
  { iata: "PWM", icao: "KPWM", name: "Portland International Jetport", city: "Portland", region: "Maine", country: "United States", countryCode: "US" },
  { iata: "BGR", icao: "KBGR", name: "Bangor International", city: "Bangor", region: "Maine", country: "United States", countryCode: "US" },
  { iata: "BTV", icao: "KBTV", name: "Patrick Leahy Burlington International", city: "Burlington", region: "Vermont", country: "United States", countryCode: "US" },
  { iata: "MHT", icao: "KMHT", name: "Manchester–Boston Regional", city: "Manchester", region: "New Hampshire", country: "United States", countryCode: "US" },
  { iata: "ORF", icao: "KORF", name: "Norfolk International", city: "Norfolk", region: "Virginia", country: "United States", countryCode: "US" },
  { iata: "RIC", icao: "KRIC", name: "Richmond International", city: "Richmond", region: "Virginia", country: "United States", countryCode: "US" },
  { iata: "ILM", icao: "KILM", name: "Wilmington International", city: "Wilmington", region: "North Carolina", country: "United States", countryCode: "US" },
  { iata: "EYW", icao: "KEYW", name: "Key West International", city: "Key West", region: "Florida", country: "United States", countryCode: "US" },
  { iata: "PNS", icao: "KPNS", name: "Pensacola International", city: "Pensacola", region: "Florida", country: "United States", countryCode: "US" },
  { iata: "SRQ", icao: "KSRQ", name: "Sarasota–Bradenton International", city: "Sarasota", region: "Florida", country: "United States", countryCode: "US" },

  // ---------------- Canada ----------------
  { iata: "YYZ", icao: "CYYZ", name: "Toronto Pearson International", city: "Toronto", region: "Ontario", country: "Canada", countryCode: "CA" },
  { iata: "YVR", icao: "CYVR", name: "Vancouver International", city: "Vancouver", region: "British Columbia", country: "Canada", countryCode: "CA" },
  { iata: "YUL", icao: "CYUL", name: "Montréal–Trudeau International", city: "Montreal", region: "Quebec", country: "Canada", countryCode: "CA" },
  { iata: "YYC", icao: "CYYC", name: "Calgary International", city: "Calgary", region: "Alberta", country: "Canada", countryCode: "CA" },
  { iata: "YEG", icao: "CYEG", name: "Edmonton International", city: "Edmonton", region: "Alberta", country: "Canada", countryCode: "CA" },
  { iata: "YOW", icao: "CYOW", name: "Ottawa Macdonald–Cartier International", city: "Ottawa", region: "Ontario", country: "Canada", countryCode: "CA" },
  { iata: "YHZ", icao: "CYHZ", name: "Halifax Stanfield International", city: "Halifax", region: "Nova Scotia", country: "Canada", countryCode: "CA" },
  { iata: "YWG", icao: "CYWG", name: "Winnipeg Richardson International", city: "Winnipeg", region: "Manitoba", country: "Canada", countryCode: "CA" },
  { iata: "YQB", icao: "CYQB", name: "Québec City Jean Lesage International", city: "Quebec City", region: "Quebec", country: "Canada", countryCode: "CA" },
  { iata: "YYJ", icao: "CYYJ", name: "Victoria International", city: "Victoria", region: "British Columbia", country: "Canada", countryCode: "CA" },

  // ---------------- Mexico / Caribbean / Central America ----------------
  { iata: "MEX", icao: "MMMX", name: "Mexico City International", city: "Mexico City", country: "Mexico", countryCode: "MX" },
  { iata: "CUN", icao: "MMUN", name: "Cancún International", city: "Cancún", country: "Mexico", countryCode: "MX" },
  { iata: "SJD", icao: "MMSD", name: "Los Cabos International", city: "San José del Cabo", country: "Mexico", countryCode: "MX" },
  { iata: "PVR", icao: "MMPR", name: "Licenciado Gustavo Díaz Ordaz International", city: "Puerto Vallarta", country: "Mexico", countryCode: "MX" },
  { iata: "GDL", icao: "MMGL", name: "Guadalajara International", city: "Guadalajara", country: "Mexico", countryCode: "MX" },
  { iata: "CZM", icao: "MMCZ", name: "Cozumel International", city: "Cozumel", country: "Mexico", countryCode: "MX" },
  { iata: "SJU", icao: "TJSJ", name: "Luis Muñoz Marín International", city: "San Juan", country: "Puerto Rico", countryCode: "PR" },
  { iata: "NAS", icao: "MYNN", name: "Lynden Pindling International", city: "Nassau", country: "Bahamas", countryCode: "BS" },
  { iata: "MBJ", icao: "MKJS", name: "Sangster International", city: "Montego Bay", country: "Jamaica", countryCode: "JM" },
  { iata: "KIN", icao: "MKJP", name: "Norman Manley International", city: "Kingston", country: "Jamaica", countryCode: "JM" },
  { iata: "PUJ", icao: "MDPC", name: "Punta Cana International", city: "Punta Cana", country: "Dominican Republic", countryCode: "DO" },
  { iata: "AUA", icao: "TNCA", name: "Queen Beatrix International", city: "Oranjestad", country: "Aruba", countryCode: "AW" },
  { iata: "CUR", icao: "TNCC", name: "Hato International", city: "Willemstad", country: "Curaçao", countryCode: "CW" },
  { iata: "PLS", icao: "MBPV", name: "Providenciales International", city: "Providenciales", country: "Turks and Caicos", countryCode: "TC" },
  { iata: "GCM", icao: "MWCR", name: "Owen Roberts International", city: "George Town", country: "Cayman Islands", countryCode: "KY" },
  { iata: "BGI", icao: "TBPB", name: "Grantley Adams International", city: "Bridgetown", country: "Barbados", countryCode: "BB" },
  { iata: "UVF", icao: "TLPL", name: "Hewanorra International", city: "Vieux Fort", country: "Saint Lucia", countryCode: "LC" },
  { iata: "ANU", icao: "TAPA", name: "V.C. Bird International", city: "St. John's", country: "Antigua and Barbuda", countryCode: "AG" },
  { iata: "SXM", icao: "TNCM", name: "Princess Juliana International", city: "Sint Maarten", country: "Sint Maarten", countryCode: "SX" },
  { iata: "LIR", icao: "MRLB", name: "Daniel Oduber Quirós International", city: "Liberia", country: "Costa Rica", countryCode: "CR" },
  { iata: "SJO", icao: "MROC", name: "Juan Santamaría International", city: "San José", country: "Costa Rica", countryCode: "CR" },
  { iata: "PTY", icao: "MPTO", name: "Tocumen International", city: "Panama City", country: "Panama", countryCode: "PA" },

  // ---------------- Europe ----------------
  { iata: "LHR", icao: "EGLL", name: "London Heathrow", city: "London", country: "United Kingdom", countryCode: "GB" },
  { iata: "LGW", icao: "EGKK", name: "London Gatwick", city: "London", country: "United Kingdom", countryCode: "GB" },
  { iata: "STN", icao: "EGSS", name: "London Stansted", city: "London", country: "United Kingdom", countryCode: "GB" },
  { iata: "MAN", icao: "EGCC", name: "Manchester", city: "Manchester", country: "United Kingdom", countryCode: "GB" },
  { iata: "EDI", icao: "EGPH", name: "Edinburgh", city: "Edinburgh", country: "United Kingdom", countryCode: "GB" },
  { iata: "DUB", icao: "EIDW", name: "Dublin", city: "Dublin", country: "Ireland", countryCode: "IE" },
  { iata: "ORK", icao: "EICK", name: "Cork", city: "Cork", country: "Ireland", countryCode: "IE" },
  { iata: "CDG", icao: "LFPG", name: "Paris Charles de Gaulle", city: "Paris", country: "France", countryCode: "FR" },
  { iata: "ORY", icao: "LFPO", name: "Paris Orly", city: "Paris", country: "France", countryCode: "FR" },
  { iata: "NCE", icao: "LFMN", name: "Nice Côte d'Azur", city: "Nice", country: "France", countryCode: "FR" },
  { iata: "LYS", icao: "LFLL", name: "Lyon–Saint-Exupéry", city: "Lyon", country: "France", countryCode: "FR" },
  { iata: "MRS", icao: "LFML", name: "Marseille Provence", city: "Marseille", country: "France", countryCode: "FR" },
  { iata: "BOD", icao: "LFBD", name: "Bordeaux–Mérignac", city: "Bordeaux", country: "France", countryCode: "FR" },
  { iata: "AMS", icao: "EHAM", name: "Amsterdam Schiphol", city: "Amsterdam", country: "Netherlands", countryCode: "NL" },
  { iata: "BRU", icao: "EBBR", name: "Brussels", city: "Brussels", country: "Belgium", countryCode: "BE" },
  { iata: "FRA", icao: "EDDF", name: "Frankfurt", city: "Frankfurt", country: "Germany", countryCode: "DE" },
  { iata: "MUC", icao: "EDDM", name: "Munich", city: "Munich", country: "Germany", countryCode: "DE" },
  { iata: "BER", icao: "EDDB", name: "Berlin Brandenburg", city: "Berlin", country: "Germany", countryCode: "DE" },
  { iata: "HAM", icao: "EDDH", name: "Hamburg", city: "Hamburg", country: "Germany", countryCode: "DE" },
  { iata: "DUS", icao: "EDDL", name: "Düsseldorf", city: "Düsseldorf", country: "Germany", countryCode: "DE" },
  { iata: "ZRH", icao: "LSZH", name: "Zürich", city: "Zürich", country: "Switzerland", countryCode: "CH" },
  { iata: "GVA", icao: "LSGG", name: "Geneva", city: "Geneva", country: "Switzerland", countryCode: "CH" },
  { iata: "VIE", icao: "LOWW", name: "Vienna International", city: "Vienna", country: "Austria", countryCode: "AT" },
  { iata: "PRG", icao: "LKPR", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic", countryCode: "CZ" },
  { iata: "BUD", icao: "LHBP", name: "Budapest Ferenc Liszt International", city: "Budapest", country: "Hungary", countryCode: "HU" },
  { iata: "WAW", icao: "EPWA", name: "Warsaw Chopin", city: "Warsaw", country: "Poland", countryCode: "PL" },
  { iata: "FCO", icao: "LIRF", name: "Rome Fiumicino", city: "Rome", country: "Italy", countryCode: "IT" },
  { iata: "MXP", icao: "LIMC", name: "Milan Malpensa", city: "Milan", country: "Italy", countryCode: "IT" },
  { iata: "LIN", icao: "LIML", name: "Milan Linate", city: "Milan", country: "Italy", countryCode: "IT" },
  { iata: "VCE", icao: "LIPZ", name: "Venice Marco Polo", city: "Venice", country: "Italy", countryCode: "IT" },
  { iata: "FLR", icao: "LIRQ", name: "Florence Peretola", city: "Florence", country: "Italy", countryCode: "IT" },
  { iata: "NAP", icao: "LIRN", name: "Naples International", city: "Naples", country: "Italy", countryCode: "IT" },
  { iata: "CTA", icao: "LICC", name: "Catania–Fontanarossa", city: "Catania", country: "Italy", countryCode: "IT" },
  { iata: "BCN", icao: "LEBL", name: "Barcelona–El Prat", city: "Barcelona", country: "Spain", countryCode: "ES" },
  { iata: "MAD", icao: "LEMD", name: "Madrid Barajas", city: "Madrid", country: "Spain", countryCode: "ES" },
  { iata: "AGP", icao: "LEMG", name: "Málaga Costa del Sol", city: "Málaga", country: "Spain", countryCode: "ES" },
  { iata: "PMI", icao: "LEPA", name: "Palma de Mallorca", city: "Palma", country: "Spain", countryCode: "ES" },
  { iata: "IBZ", icao: "LEIB", name: "Ibiza", city: "Ibiza", country: "Spain", countryCode: "ES" },
  { iata: "LIS", icao: "LPPT", name: "Humberto Delgado (Lisbon)", city: "Lisbon", country: "Portugal", countryCode: "PT" },
  { iata: "OPO", icao: "LPPR", name: "Francisco Sá Carneiro (Porto)", city: "Porto", country: "Portugal", countryCode: "PT" },
  { iata: "FNC", icao: "LPMA", name: "Madeira", city: "Funchal", country: "Portugal", countryCode: "PT" },
  { iata: "ATH", icao: "LGAV", name: "Athens International", city: "Athens", country: "Greece", countryCode: "GR" },
  { iata: "JTR", icao: "LGSR", name: "Santorini (Thira)", city: "Santorini", country: "Greece", countryCode: "GR" },
  { iata: "JMK", icao: "LGMK", name: "Mykonos", city: "Mykonos", country: "Greece", countryCode: "GR" },
  { iata: "HER", icao: "LGIR", name: "Heraklion International", city: "Heraklion", country: "Greece", countryCode: "GR" },
  { iata: "IST", icao: "LTFM", name: "Istanbul Airport", city: "Istanbul", country: "Turkey", countryCode: "TR" },
  { iata: "SAW", icao: "LTFJ", name: "Sabiha Gökçen International", city: "Istanbul", country: "Turkey", countryCode: "TR" },
  { iata: "CPH", icao: "EKCH", name: "Copenhagen", city: "Copenhagen", country: "Denmark", countryCode: "DK" },
  { iata: "ARN", icao: "ESSA", name: "Stockholm Arlanda", city: "Stockholm", country: "Sweden", countryCode: "SE" },
  { iata: "OSL", icao: "ENGM", name: "Oslo Gardermoen", city: "Oslo", country: "Norway", countryCode: "NO" },
  { iata: "HEL", icao: "EFHK", name: "Helsinki-Vantaa", city: "Helsinki", country: "Finland", countryCode: "FI" },
  { iata: "KEF", icao: "BIKF", name: "Keflavík International", city: "Reykjavík", country: "Iceland", countryCode: "IS" },

  // ---------------- Middle East / Africa ----------------
  { iata: "DXB", icao: "OMDB", name: "Dubai International", city: "Dubai", country: "United Arab Emirates", countryCode: "AE" },
  { iata: "AUH", icao: "OMAA", name: "Zayed International", city: "Abu Dhabi", country: "United Arab Emirates", countryCode: "AE" },
  { iata: "DOH", icao: "OTHH", name: "Hamad International", city: "Doha", country: "Qatar", countryCode: "QA" },
  { iata: "TLV", icao: "LLBG", name: "Ben Gurion", city: "Tel Aviv", country: "Israel", countryCode: "IL" },
  { iata: "AMM", icao: "OJAI", name: "Queen Alia International", city: "Amman", country: "Jordan", countryCode: "JO" },
  { iata: "CAI", icao: "HECA", name: "Cairo International", city: "Cairo", country: "Egypt", countryCode: "EG" },
  { iata: "CMN", icao: "GMMN", name: "Mohammed V International", city: "Casablanca", country: "Morocco", countryCode: "MA" },
  { iata: "RAK", icao: "GMMX", name: "Marrakesh Menara", city: "Marrakesh", country: "Morocco", countryCode: "MA" },
  { iata: "JNB", icao: "FAOR", name: "O.R. Tambo International", city: "Johannesburg", country: "South Africa", countryCode: "ZA" },
  { iata: "CPT", icao: "FACT", name: "Cape Town International", city: "Cape Town", country: "South Africa", countryCode: "ZA" },
  { iata: "NBO", icao: "HKJK", name: "Jomo Kenyatta International", city: "Nairobi", country: "Kenya", countryCode: "KE" },

  // ---------------- Asia / Pacific ----------------
  { iata: "NRT", icao: "RJAA", name: "Narita International", city: "Tokyo", country: "Japan", countryCode: "JP" },
  { iata: "HND", icao: "RJTT", name: "Haneda (Tokyo International)", city: "Tokyo", country: "Japan", countryCode: "JP" },
  { iata: "KIX", icao: "RJBB", name: "Kansai International", city: "Osaka", country: "Japan", countryCode: "JP" },
  { iata: "ITM", icao: "RJOO", name: "Itami (Osaka International)", city: "Osaka", country: "Japan", countryCode: "JP" },
  { iata: "NGO", icao: "RJGG", name: "Chubu Centrair International", city: "Nagoya", country: "Japan", countryCode: "JP" },
  { iata: "ICN", icao: "RKSI", name: "Incheon International", city: "Seoul", country: "South Korea", countryCode: "KR" },
  { iata: "GMP", icao: "RKSS", name: "Gimpo International", city: "Seoul", country: "South Korea", countryCode: "KR" },
  { iata: "PEK", icao: "ZBAA", name: "Beijing Capital International", city: "Beijing", country: "China", countryCode: "CN" },
  { iata: "PKX", icao: "ZBAD", name: "Beijing Daxing International", city: "Beijing", country: "China", countryCode: "CN" },
  { iata: "PVG", icao: "ZSPD", name: "Shanghai Pudong International", city: "Shanghai", country: "China", countryCode: "CN" },
  { iata: "CAN", icao: "ZGGG", name: "Guangzhou Baiyun International", city: "Guangzhou", country: "China", countryCode: "CN" },
  { iata: "HKG", icao: "VHHH", name: "Hong Kong International", city: "Hong Kong", country: "Hong Kong", countryCode: "HK" },
  { iata: "TPE", icao: "RCTP", name: "Taiwan Taoyuan International", city: "Taipei", country: "Taiwan", countryCode: "TW" },
  { iata: "SIN", icao: "WSSS", name: "Singapore Changi", city: "Singapore", country: "Singapore", countryCode: "SG" },
  { iata: "BKK", icao: "VTBS", name: "Suvarnabhumi", city: "Bangkok", country: "Thailand", countryCode: "TH" },
  { iata: "HKT", icao: "VTSP", name: "Phuket International", city: "Phuket", country: "Thailand", countryCode: "TH" },
  { iata: "KUL", icao: "WMKK", name: "Kuala Lumpur International", city: "Kuala Lumpur", country: "Malaysia", countryCode: "MY" },
  { iata: "DPS", icao: "WADD", name: "Ngurah Rai (Bali)", city: "Denpasar", country: "Indonesia", countryCode: "ID" },
  { iata: "CGK", icao: "WIII", name: "Soekarno–Hatta International", city: "Jakarta", country: "Indonesia", countryCode: "ID" },
  { iata: "MNL", icao: "RPLL", name: "Ninoy Aquino International", city: "Manila", country: "Philippines", countryCode: "PH" },
  { iata: "SGN", icao: "VVTS", name: "Tan Son Nhat International", city: "Ho Chi Minh City", country: "Vietnam", countryCode: "VN" },
  { iata: "HAN", icao: "VVNB", name: "Noi Bai International", city: "Hanoi", country: "Vietnam", countryCode: "VN" },
  { iata: "DEL", icao: "VIDP", name: "Indira Gandhi International", city: "Delhi", country: "India", countryCode: "IN" },
  { iata: "BOM", icao: "VABB", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai", country: "India", countryCode: "IN" },
  { iata: "SYD", icao: "YSSY", name: "Sydney Kingsford Smith", city: "Sydney", country: "Australia", countryCode: "AU" },
  { iata: "MEL", icao: "YMML", name: "Melbourne", city: "Melbourne", country: "Australia", countryCode: "AU" },
  { iata: "BNE", icao: "YBBN", name: "Brisbane", city: "Brisbane", country: "Australia", countryCode: "AU" },
  { iata: "PER", icao: "YPPH", name: "Perth", city: "Perth", country: "Australia", countryCode: "AU" },
  { iata: "AKL", icao: "NZAA", name: "Auckland", city: "Auckland", country: "New Zealand", countryCode: "NZ" },
  { iata: "ZQN", icao: "NZQN", name: "Queenstown", city: "Queenstown", country: "New Zealand", countryCode: "NZ" },
  { iata: "NAN", icao: "NFFN", name: "Nadi International", city: "Nadi", country: "Fiji", countryCode: "FJ" },
  { iata: "PPT", icao: "NTAA", name: "Faa'a International", city: "Papeete", country: "French Polynesia", countryCode: "PF" },

  // ---------------- South America ----------------
  { iata: "GRU", icao: "SBGR", name: "São Paulo/Guarulhos International", city: "São Paulo", country: "Brazil", countryCode: "BR" },
  { iata: "GIG", icao: "SBGL", name: "Rio de Janeiro/Galeão", city: "Rio de Janeiro", country: "Brazil", countryCode: "BR" },
  { iata: "EZE", icao: "SAEZ", name: "Ministro Pistarini (Ezeiza)", city: "Buenos Aires", country: "Argentina", countryCode: "AR" },
  { iata: "SCL", icao: "SCEL", name: "Arturo Merino Benítez", city: "Santiago", country: "Chile", countryCode: "CL" },
  { iata: "LIM", icao: "SPJC", name: "Jorge Chávez International", city: "Lima", country: "Peru", countryCode: "PE" },
  { iata: "CUZ", icao: "SPZO", name: "Alejandro Velasco Astete International", city: "Cusco", country: "Peru", countryCode: "PE" },
  { iata: "BOG", icao: "SKBO", name: "El Dorado International", city: "Bogotá", country: "Colombia", countryCode: "CO" },
  { iata: "CTG", icao: "SKCG", name: "Rafael Núñez International", city: "Cartagena", country: "Colombia", countryCode: "CO" },
  { iata: "UIO", icao: "SEQM", name: "Mariscal Sucre International", city: "Quito", country: "Ecuador", countryCode: "EC" },
];
