/** Initial destination catalog — idempotently upserted on first start. Admins can edit, add, or deactivate in the UI. */

import type { DestinationType } from "@prisma/client";

export interface DestinationSeed {
  slug: string;
  name: string;
  type: DestinationType;
  country?: string;
  region?: string;
  /** Comma-separated aliases to help search ("WDW, Disney World, Walt Disney") */
  aliases?: string;
}

export const DESTINATION_SEED: DestinationSeed[] = [
  // ================= Theme parks & major venues =================
  { slug: "walt-disney-world", name: "Walt Disney World", type: "PARK", country: "United States", region: "Florida", aliases: "WDW, Disney, Orlando, Magic Kingdom, EPCOT, Hollywood Studios, Animal Kingdom" },
  { slug: "disneyland-resort", name: "Disneyland Resort (California)", type: "PARK", country: "United States", region: "California", aliases: "Disneyland, Anaheim, California Adventure" },
  { slug: "universal-orlando", name: "Universal Orlando Resort", type: "PARK", country: "United States", region: "Florida", aliases: "Universal Studios, Islands of Adventure, Epic Universe, Harry Potter" },
  { slug: "universal-hollywood", name: "Universal Studios Hollywood", type: "PARK", country: "United States", region: "California", aliases: "Universal LA" },
  { slug: "seaworld-orlando", name: "SeaWorld Orlando", type: "PARK", country: "United States", region: "Florida" },
  { slug: "busch-gardens-tampa", name: "Busch Gardens Tampa Bay", type: "PARK", country: "United States", region: "Florida" },
  { slug: "legoland-florida", name: "LEGOLAND Florida", type: "PARK", country: "United States", region: "Florida" },
  { slug: "disneyland-paris", name: "Disneyland Paris", type: "PARK", country: "France", aliases: "EuroDisney" },
  { slug: "tokyo-disney", name: "Tokyo Disney Resort", type: "PARK", country: "Japan", aliases: "Tokyo Disneyland, DisneySea" },
  { slug: "hong-kong-disneyland", name: "Hong Kong Disneyland", type: "PARK", country: "Hong Kong" },
  { slug: "shanghai-disneyland", name: "Shanghai Disneyland", type: "PARK", country: "China" },
  { slug: "universal-beijing", name: "Universal Beijing Resort", type: "PARK", country: "China" },
  { slug: "cedar-point", name: "Cedar Point", type: "PARK", country: "United States", region: "Ohio" },
  { slug: "dollywood", name: "Dollywood", type: "PARK", country: "United States", region: "Tennessee" },

  // ================= US cruise-style / river cities used as embarkation =================
  { slug: "port-canaveral", name: "Port Canaveral (cruise port)", type: "VENUE", country: "United States", region: "Florida", aliases: "cruise, Disney Cruise Line, Carnival" },
  { slug: "port-of-miami", name: "PortMiami (cruise port)", type: "VENUE", country: "United States", region: "Florida" },
  { slug: "port-everglades", name: "Port Everglades (cruise port)", type: "VENUE", country: "United States", region: "Florida" },
  { slug: "galveston-cruise", name: "Galveston Cruise Port", type: "VENUE", country: "United States", region: "Texas" },

  // ================= Continents / big areas =================
  { slug: "western-europe", name: "Western Europe", type: "AREA", aliases: "Europe" },
  { slug: "eastern-europe", name: "Eastern Europe", type: "AREA" },
  { slug: "mediterranean", name: "Mediterranean", type: "AREA" },
  { slug: "scandinavia", name: "Scandinavia", type: "AREA", aliases: "Nordic, Norway, Sweden, Denmark, Finland, Iceland" },
  { slug: "british-isles", name: "British Isles", type: "AREA", aliases: "UK, Ireland" },
  { slug: "caribbean", name: "Caribbean", type: "AREA" },
  { slug: "central-america", name: "Central America", type: "AREA" },
  { slug: "south-america", name: "South America", type: "AREA" },
  { slug: "southeast-asia", name: "Southeast Asia", type: "AREA" },
  { slug: "east-asia", name: "East Asia", type: "AREA" },
  { slug: "south-pacific", name: "South Pacific", type: "AREA", aliases: "Oceania, Polynesia" },
  { slug: "middle-east", name: "Middle East", type: "AREA" },
  { slug: "east-africa", name: "East Africa", type: "AREA", aliases: "Kenya, Tanzania, safari" },
  { slug: "southern-africa", name: "Southern Africa", type: "AREA", aliases: "South Africa, Botswana, Namibia, safari" },
  { slug: "us-national-parks", name: "US National Parks", type: "AREA", country: "United States" },

  // ================= Countries (popular travel markets) =================
  { slug: "united-states", name: "United States", type: "COUNTRY", country: "United States", aliases: "USA, US, America" },
  { slug: "canada", name: "Canada", type: "COUNTRY", country: "Canada" },
  { slug: "mexico", name: "Mexico", type: "COUNTRY", country: "Mexico" },
  { slug: "united-kingdom", name: "United Kingdom", type: "COUNTRY", country: "United Kingdom", aliases: "UK, England, Scotland, Wales, Britain" },
  { slug: "ireland", name: "Ireland", type: "COUNTRY", country: "Ireland" },
  { slug: "france", name: "France", type: "COUNTRY", country: "France" },
  { slug: "italy", name: "Italy", type: "COUNTRY", country: "Italy" },
  { slug: "spain", name: "Spain", type: "COUNTRY", country: "Spain" },
  { slug: "portugal", name: "Portugal", type: "COUNTRY", country: "Portugal" },
  { slug: "greece", name: "Greece", type: "COUNTRY", country: "Greece" },
  { slug: "croatia", name: "Croatia", type: "COUNTRY", country: "Croatia" },
  { slug: "turkey", name: "Turkey", type: "COUNTRY", country: "Turkey" },
  { slug: "netherlands", name: "Netherlands", type: "COUNTRY", country: "Netherlands", aliases: "Holland" },
  { slug: "belgium", name: "Belgium", type: "COUNTRY", country: "Belgium" },
  { slug: "germany", name: "Germany", type: "COUNTRY", country: "Germany" },
  { slug: "switzerland", name: "Switzerland", type: "COUNTRY", country: "Switzerland" },
  { slug: "austria", name: "Austria", type: "COUNTRY", country: "Austria" },
  { slug: "czech-republic", name: "Czech Republic", type: "COUNTRY", country: "Czech Republic", aliases: "Czechia" },
  { slug: "hungary", name: "Hungary", type: "COUNTRY", country: "Hungary" },
  { slug: "poland", name: "Poland", type: "COUNTRY", country: "Poland" },
  { slug: "norway", name: "Norway", type: "COUNTRY", country: "Norway" },
  { slug: "sweden", name: "Sweden", type: "COUNTRY", country: "Sweden" },
  { slug: "denmark", name: "Denmark", type: "COUNTRY", country: "Denmark" },
  { slug: "finland", name: "Finland", type: "COUNTRY", country: "Finland" },
  { slug: "iceland", name: "Iceland", type: "COUNTRY", country: "Iceland" },
  { slug: "morocco", name: "Morocco", type: "COUNTRY", country: "Morocco" },
  { slug: "egypt", name: "Egypt", type: "COUNTRY", country: "Egypt" },
  { slug: "south-africa", name: "South Africa", type: "COUNTRY", country: "South Africa" },
  { slug: "kenya", name: "Kenya", type: "COUNTRY", country: "Kenya" },
  { slug: "tanzania", name: "Tanzania", type: "COUNTRY", country: "Tanzania", aliases: "Serengeti, Zanzibar" },
  { slug: "uae", name: "United Arab Emirates", type: "COUNTRY", country: "United Arab Emirates", aliases: "Dubai, Abu Dhabi" },
  { slug: "jordan", name: "Jordan", type: "COUNTRY", country: "Jordan", aliases: "Petra" },
  { slug: "israel", name: "Israel", type: "COUNTRY", country: "Israel" },
  { slug: "japan", name: "Japan", type: "COUNTRY", country: "Japan" },
  { slug: "south-korea", name: "South Korea", type: "COUNTRY", country: "South Korea" },
  { slug: "china", name: "China", type: "COUNTRY", country: "China" },
  { slug: "thailand", name: "Thailand", type: "COUNTRY", country: "Thailand" },
  { slug: "vietnam", name: "Vietnam", type: "COUNTRY", country: "Vietnam" },
  { slug: "indonesia", name: "Indonesia", type: "COUNTRY", country: "Indonesia", aliases: "Bali" },
  { slug: "singapore", name: "Singapore", type: "COUNTRY", country: "Singapore" },
  { slug: "india", name: "India", type: "COUNTRY", country: "India" },
  { slug: "australia", name: "Australia", type: "COUNTRY", country: "Australia" },
  { slug: "new-zealand", name: "New Zealand", type: "COUNTRY", country: "New Zealand" },
  { slug: "fiji", name: "Fiji", type: "COUNTRY", country: "Fiji" },
  { slug: "french-polynesia", name: "French Polynesia", type: "COUNTRY", country: "French Polynesia", aliases: "Tahiti, Bora Bora, Moorea" },
  { slug: "costa-rica", name: "Costa Rica", type: "COUNTRY", country: "Costa Rica" },
  { slug: "panama", name: "Panama", type: "COUNTRY", country: "Panama" },
  { slug: "belize", name: "Belize", type: "COUNTRY", country: "Belize" },
  { slug: "brazil", name: "Brazil", type: "COUNTRY", country: "Brazil" },
  { slug: "argentina", name: "Argentina", type: "COUNTRY", country: "Argentina" },
  { slug: "chile", name: "Chile", type: "COUNTRY", country: "Chile", aliases: "Patagonia, Atacama" },
  { slug: "peru", name: "Peru", type: "COUNTRY", country: "Peru", aliases: "Machu Picchu, Cusco, Sacred Valley" },
  { slug: "colombia", name: "Colombia", type: "COUNTRY", country: "Colombia" },
  { slug: "ecuador", name: "Ecuador", type: "COUNTRY", country: "Ecuador", aliases: "Galapagos" },
  { slug: "bahamas", name: "Bahamas", type: "COUNTRY", country: "Bahamas" },
  { slug: "jamaica", name: "Jamaica", type: "COUNTRY", country: "Jamaica" },
  { slug: "dominican-republic", name: "Dominican Republic", type: "COUNTRY", country: "Dominican Republic", aliases: "Punta Cana" },
  { slug: "barbados", name: "Barbados", type: "COUNTRY", country: "Barbados" },
  { slug: "saint-lucia", name: "Saint Lucia", type: "COUNTRY", country: "Saint Lucia" },
  { slug: "aruba", name: "Aruba", type: "COUNTRY", country: "Aruba" },
  { slug: "turks-caicos", name: "Turks and Caicos", type: "COUNTRY", country: "Turks and Caicos" },
  { slug: "cayman-islands", name: "Cayman Islands", type: "COUNTRY", country: "Cayman Islands" },
  { slug: "puerto-rico", name: "Puerto Rico", type: "REGION", country: "United States" },

  // ================= US states (selection often used as destinations) =================
  { slug: "alabama", name: "Alabama", type: "REGION", country: "United States" },
  { slug: "alaska", name: "Alaska", type: "REGION", country: "United States" },
  { slug: "arizona", name: "Arizona", type: "REGION", country: "United States" },
  { slug: "arkansas", name: "Arkansas", type: "REGION", country: "United States" },
  { slug: "california", name: "California", type: "REGION", country: "United States" },
  { slug: "colorado", name: "Colorado", type: "REGION", country: "United States" },
  { slug: "connecticut", name: "Connecticut", type: "REGION", country: "United States" },
  { slug: "delaware", name: "Delaware", type: "REGION", country: "United States" },
  { slug: "florida", name: "Florida", type: "REGION", country: "United States" },
  { slug: "georgia", name: "Georgia", type: "REGION", country: "United States" },
  { slug: "hawaii", name: "Hawaii", type: "REGION", country: "United States" },
  { slug: "idaho", name: "Idaho", type: "REGION", country: "United States" },
  { slug: "illinois", name: "Illinois", type: "REGION", country: "United States" },
  { slug: "indiana", name: "Indiana", type: "REGION", country: "United States" },
  { slug: "iowa", name: "Iowa", type: "REGION", country: "United States" },
  { slug: "kansas", name: "Kansas", type: "REGION", country: "United States" },
  { slug: "kentucky", name: "Kentucky", type: "REGION", country: "United States" },
  { slug: "louisiana", name: "Louisiana", type: "REGION", country: "United States" },
  { slug: "maine", name: "Maine", type: "REGION", country: "United States" },
  { slug: "maryland", name: "Maryland", type: "REGION", country: "United States" },
  { slug: "massachusetts", name: "Massachusetts", type: "REGION", country: "United States" },
  { slug: "michigan", name: "Michigan", type: "REGION", country: "United States" },
  { slug: "minnesota", name: "Minnesota", type: "REGION", country: "United States" },
  { slug: "mississippi", name: "Mississippi", type: "REGION", country: "United States" },
  { slug: "missouri", name: "Missouri", type: "REGION", country: "United States" },
  { slug: "montana", name: "Montana", type: "REGION", country: "United States" },
  { slug: "nebraska", name: "Nebraska", type: "REGION", country: "United States" },
  { slug: "nevada", name: "Nevada", type: "REGION", country: "United States" },
  { slug: "new-hampshire", name: "New Hampshire", type: "REGION", country: "United States" },
  { slug: "new-jersey", name: "New Jersey", type: "REGION", country: "United States" },
  { slug: "new-mexico", name: "New Mexico", type: "REGION", country: "United States" },
  { slug: "new-york-state", name: "New York (state)", type: "REGION", country: "United States" },
  { slug: "north-carolina", name: "North Carolina", type: "REGION", country: "United States" },
  { slug: "north-dakota", name: "North Dakota", type: "REGION", country: "United States" },
  { slug: "ohio", name: "Ohio", type: "REGION", country: "United States" },
  { slug: "oklahoma", name: "Oklahoma", type: "REGION", country: "United States" },
  { slug: "oregon", name: "Oregon", type: "REGION", country: "United States" },
  { slug: "pennsylvania", name: "Pennsylvania", type: "REGION", country: "United States" },
  { slug: "rhode-island", name: "Rhode Island", type: "REGION", country: "United States" },
  { slug: "south-carolina", name: "South Carolina", type: "REGION", country: "United States" },
  { slug: "south-dakota", name: "South Dakota", type: "REGION", country: "United States" },
  { slug: "tennessee", name: "Tennessee", type: "REGION", country: "United States" },
  { slug: "texas", name: "Texas", type: "REGION", country: "United States" },
  { slug: "utah", name: "Utah", type: "REGION", country: "United States" },
  { slug: "vermont", name: "Vermont", type: "REGION", country: "United States" },
  { slug: "virginia", name: "Virginia", type: "REGION", country: "United States" },
  { slug: "washington-state", name: "Washington (state)", type: "REGION", country: "United States" },
  { slug: "west-virginia", name: "West Virginia", type: "REGION", country: "United States" },
  { slug: "wisconsin", name: "Wisconsin", type: "REGION", country: "United States" },
  { slug: "wyoming", name: "Wyoming", type: "REGION", country: "United States" },
  { slug: "dc", name: "Washington, D.C.", type: "CITY", country: "United States", region: "District of Columbia", aliases: "DC, Washington" },

  // ================= Major cities & resort areas =================
  // US
  { slug: "orlando", name: "Orlando", type: "CITY", country: "United States", region: "Florida", aliases: "Orlando FL, Disney, Universal" },
  { slug: "miami", name: "Miami", type: "CITY", country: "United States", region: "Florida" },
  { slug: "miami-beach", name: "Miami Beach", type: "CITY", country: "United States", region: "Florida", aliases: "South Beach" },
  { slug: "key-west", name: "Key West", type: "CITY", country: "United States", region: "Florida", aliases: "Florida Keys" },
  { slug: "florida-keys", name: "Florida Keys", type: "AREA", country: "United States", region: "Florida" },
  { slug: "naples-fl", name: "Naples (FL)", type: "CITY", country: "United States", region: "Florida" },
  { slug: "destin", name: "Destin", type: "CITY", country: "United States", region: "Florida", aliases: "30A, Emerald Coast" },
  { slug: "30a", name: "30A / Seaside / Rosemary Beach", type: "AREA", country: "United States", region: "Florida" },
  { slug: "new-york-city", name: "New York City", type: "CITY", country: "United States", region: "New York", aliases: "NYC, Manhattan, Brooklyn" },
  { slug: "hamptons", name: "The Hamptons", type: "AREA", country: "United States", region: "New York" },
  { slug: "boston", name: "Boston", type: "CITY", country: "United States", region: "Massachusetts" },
  { slug: "cape-cod", name: "Cape Cod", type: "AREA", country: "United States", region: "Massachusetts", aliases: "Nantucket, Martha's Vineyard" },
  { slug: "nantucket", name: "Nantucket", type: "CITY", country: "United States", region: "Massachusetts" },
  { slug: "marthas-vineyard", name: "Martha's Vineyard", type: "CITY", country: "United States", region: "Massachusetts" },
  { slug: "newport-ri", name: "Newport (RI)", type: "CITY", country: "United States", region: "Rhode Island" },
  { slug: "charleston", name: "Charleston", type: "CITY", country: "United States", region: "South Carolina" },
  { slug: "savannah", name: "Savannah", type: "CITY", country: "United States", region: "Georgia" },
  { slug: "nashville", name: "Nashville", type: "CITY", country: "United States", region: "Tennessee" },
  { slug: "gatlinburg-smokies", name: "Gatlinburg / Great Smoky Mountains", type: "AREA", country: "United States", region: "Tennessee" },
  { slug: "new-orleans", name: "New Orleans", type: "CITY", country: "United States", region: "Louisiana", aliases: "NOLA" },
  { slug: "austin", name: "Austin", type: "CITY", country: "United States", region: "Texas" },
  { slug: "san-antonio", name: "San Antonio", type: "CITY", country: "United States", region: "Texas" },
  { slug: "dallas", name: "Dallas", type: "CITY", country: "United States", region: "Texas" },
  { slug: "chicago", name: "Chicago", type: "CITY", country: "United States", region: "Illinois" },
  { slug: "washington-dc", name: "Washington, D.C.", type: "CITY", country: "United States", region: "District of Columbia" },
  { slug: "las-vegas", name: "Las Vegas", type: "CITY", country: "United States", region: "Nevada", aliases: "Vegas, Strip" },
  { slug: "lake-tahoe", name: "Lake Tahoe", type: "AREA", country: "United States", region: "California" },
  { slug: "los-angeles", name: "Los Angeles", type: "CITY", country: "United States", region: "California", aliases: "LA, Hollywood, Santa Monica" },
  { slug: "san-diego", name: "San Diego", type: "CITY", country: "United States", region: "California" },
  { slug: "san-francisco", name: "San Francisco", type: "CITY", country: "United States", region: "California", aliases: "SF, Bay Area" },
  { slug: "napa-sonoma", name: "Napa & Sonoma (Wine Country)", type: "AREA", country: "United States", region: "California" },
  { slug: "big-sur", name: "Big Sur", type: "AREA", country: "United States", region: "California" },
  { slug: "santa-barbara", name: "Santa Barbara", type: "CITY", country: "United States", region: "California" },
  { slug: "palm-springs", name: "Palm Springs", type: "CITY", country: "United States", region: "California" },
  { slug: "seattle", name: "Seattle", type: "CITY", country: "United States", region: "Washington" },
  { slug: "portland-or", name: "Portland (OR)", type: "CITY", country: "United States", region: "Oregon" },
  { slug: "grand-canyon", name: "Grand Canyon", type: "AREA", country: "United States", region: "Arizona" },
  { slug: "sedona", name: "Sedona", type: "CITY", country: "United States", region: "Arizona" },
  { slug: "scottsdale", name: "Scottsdale", type: "CITY", country: "United States", region: "Arizona" },
  { slug: "yellowstone", name: "Yellowstone National Park", type: "AREA", country: "United States", region: "Wyoming" },
  { slug: "jackson-hole", name: "Jackson Hole", type: "CITY", country: "United States", region: "Wyoming", aliases: "Grand Teton" },
  { slug: "aspen", name: "Aspen / Snowmass", type: "CITY", country: "United States", region: "Colorado" },
  { slug: "vail-beaver-creek", name: "Vail / Beaver Creek", type: "CITY", country: "United States", region: "Colorado" },
  { slug: "telluride", name: "Telluride", type: "CITY", country: "United States", region: "Colorado" },
  { slug: "breckenridge", name: "Breckenridge", type: "CITY", country: "United States", region: "Colorado" },
  { slug: "park-city", name: "Park City", type: "CITY", country: "United States", region: "Utah" },
  { slug: "zion", name: "Zion National Park", type: "AREA", country: "United States", region: "Utah" },
  { slug: "bryce-canyon", name: "Bryce Canyon National Park", type: "AREA", country: "United States", region: "Utah" },
  { slug: "yosemite", name: "Yosemite National Park", type: "AREA", country: "United States", region: "California" },
  { slug: "glacier-national-park", name: "Glacier National Park", type: "AREA", country: "United States", region: "Montana" },
  { slug: "acadia", name: "Acadia National Park", type: "AREA", country: "United States", region: "Maine" },
  { slug: "kennebunkport", name: "Kennebunkport", type: "CITY", country: "United States", region: "Maine" },
  // Hawaii islands
  { slug: "oahu", name: "Oahu (Honolulu / Waikiki)", type: "AREA", country: "United States", region: "Hawaii" },
  { slug: "maui", name: "Maui", type: "AREA", country: "United States", region: "Hawaii" },
  { slug: "kauai", name: "Kauai", type: "AREA", country: "United States", region: "Hawaii" },
  { slug: "big-island", name: "Big Island (Hawaii)", type: "AREA", country: "United States", region: "Hawaii" },
  { slug: "lanai", name: "Lanai", type: "AREA", country: "United States", region: "Hawaii" },
  // Alaska
  { slug: "anchorage", name: "Anchorage", type: "CITY", country: "United States", region: "Alaska" },
  { slug: "denali", name: "Denali National Park", type: "AREA", country: "United States", region: "Alaska" },
  { slug: "inside-passage", name: "Alaska Inside Passage", type: "AREA", country: "United States", region: "Alaska" },

  // Canada
  { slug: "toronto", name: "Toronto", type: "CITY", country: "Canada", region: "Ontario" },
  { slug: "vancouver", name: "Vancouver", type: "CITY", country: "Canada", region: "British Columbia" },
  { slug: "whistler", name: "Whistler", type: "CITY", country: "Canada", region: "British Columbia" },
  { slug: "banff", name: "Banff & Lake Louise", type: "AREA", country: "Canada", region: "Alberta" },
  { slug: "montreal", name: "Montreal", type: "CITY", country: "Canada", region: "Quebec" },
  { slug: "quebec-city", name: "Quebec City", type: "CITY", country: "Canada", region: "Quebec" },

  // Mexico / Caribbean
  { slug: "cancun", name: "Cancún", type: "CITY", country: "Mexico", aliases: "Cancun" },
  { slug: "playa-del-carmen", name: "Playa del Carmen", type: "CITY", country: "Mexico" },
  { slug: "tulum", name: "Tulum", type: "CITY", country: "Mexico" },
  { slug: "riviera-maya", name: "Riviera Maya", type: "AREA", country: "Mexico" },
  { slug: "cozumel", name: "Cozumel", type: "CITY", country: "Mexico" },
  { slug: "cabo", name: "Los Cabos / Cabo San Lucas", type: "CITY", country: "Mexico" },
  { slug: "puerto-vallarta", name: "Puerto Vallarta", type: "CITY", country: "Mexico" },
  { slug: "mexico-city", name: "Mexico City", type: "CITY", country: "Mexico", aliases: "CDMX" },
  { slug: "punta-cana", name: "Punta Cana", type: "CITY", country: "Dominican Republic" },
  { slug: "nassau", name: "Nassau", type: "CITY", country: "Bahamas" },
  { slug: "exuma", name: "Exuma", type: "CITY", country: "Bahamas" },
  { slug: "st-lucia", name: "Saint Lucia", type: "CITY", country: "Saint Lucia" },
  { slug: "st-martin", name: "St. Martin / Sint Maarten", type: "CITY", country: "Sint Maarten" },
  { slug: "grand-cayman", name: "Grand Cayman", type: "CITY", country: "Cayman Islands", aliases: "Seven Mile Beach" },
  { slug: "providenciales", name: "Providenciales (Turks & Caicos)", type: "CITY", country: "Turks and Caicos", aliases: "Turks Caicos, Grace Bay" },
  { slug: "bvi", name: "British Virgin Islands", type: "AREA", country: "British Virgin Islands" },
  { slug: "usvi", name: "US Virgin Islands", type: "AREA", country: "United States", aliases: "St. Thomas, St. John, St. Croix" },

  // Europe
  { slug: "london", name: "London", type: "CITY", country: "United Kingdom" },
  { slug: "edinburgh", name: "Edinburgh", type: "CITY", country: "United Kingdom" },
  { slug: "scottish-highlands", name: "Scottish Highlands", type: "AREA", country: "United Kingdom" },
  { slug: "dublin", name: "Dublin", type: "CITY", country: "Ireland" },
  { slug: "cotswolds", name: "Cotswolds", type: "AREA", country: "United Kingdom" },
  { slug: "paris", name: "Paris", type: "CITY", country: "France" },
  { slug: "provence", name: "Provence", type: "AREA", country: "France" },
  { slug: "french-riviera", name: "French Riviera (Côte d'Azur)", type: "AREA", country: "France", aliases: "Nice, Cannes, Saint-Tropez, Monaco" },
  { slug: "loire-valley", name: "Loire Valley", type: "AREA", country: "France" },
  { slug: "normandy", name: "Normandy", type: "AREA", country: "France" },
  { slug: "amsterdam", name: "Amsterdam", type: "CITY", country: "Netherlands" },
  { slug: "brussels-bruges", name: "Brussels & Bruges", type: "AREA", country: "Belgium" },
  { slug: "rome", name: "Rome", type: "CITY", country: "Italy" },
  { slug: "florence", name: "Florence", type: "CITY", country: "Italy" },
  { slug: "tuscany", name: "Tuscany", type: "AREA", country: "Italy" },
  { slug: "venice", name: "Venice", type: "CITY", country: "Italy" },
  { slug: "amalfi-coast", name: "Amalfi Coast", type: "AREA", country: "Italy", aliases: "Positano, Capri, Sorrento" },
  { slug: "sicily", name: "Sicily", type: "AREA", country: "Italy" },
  { slug: "sardinia", name: "Sardinia", type: "AREA", country: "Italy" },
  { slug: "lake-como", name: "Lake Como", type: "AREA", country: "Italy" },
  { slug: "barcelona", name: "Barcelona", type: "CITY", country: "Spain" },
  { slug: "madrid", name: "Madrid", type: "CITY", country: "Spain" },
  { slug: "seville", name: "Seville & Andalusia", type: "CITY", country: "Spain" },
  { slug: "mallorca", name: "Mallorca", type: "AREA", country: "Spain" },
  { slug: "ibiza", name: "Ibiza", type: "AREA", country: "Spain" },
  { slug: "lisbon", name: "Lisbon", type: "CITY", country: "Portugal" },
  { slug: "porto", name: "Porto", type: "CITY", country: "Portugal" },
  { slug: "douro-valley", name: "Douro Valley", type: "AREA", country: "Portugal" },
  { slug: "algarve", name: "Algarve", type: "AREA", country: "Portugal" },
  { slug: "athens", name: "Athens", type: "CITY", country: "Greece" },
  { slug: "santorini", name: "Santorini", type: "CITY", country: "Greece" },
  { slug: "mykonos", name: "Mykonos", type: "CITY", country: "Greece" },
  { slug: "crete", name: "Crete", type: "AREA", country: "Greece" },
  { slug: "istanbul", name: "Istanbul", type: "CITY", country: "Turkey" },
  { slug: "cappadocia", name: "Cappadocia", type: "AREA", country: "Turkey" },
  { slug: "swiss-alps", name: "Swiss Alps", type: "AREA", country: "Switzerland", aliases: "Zermatt, St. Moritz, Gstaad" },
  { slug: "vienna", name: "Vienna", type: "CITY", country: "Austria" },
  { slug: "salzburg", name: "Salzburg", type: "CITY", country: "Austria" },
  { slug: "prague", name: "Prague", type: "CITY", country: "Czech Republic" },
  { slug: "budapest", name: "Budapest", type: "CITY", country: "Hungary" },
  { slug: "reykjavik", name: "Reykjavík", type: "CITY", country: "Iceland" },
  { slug: "bavaria", name: "Bavaria (Munich, Neuschwanstein)", type: "AREA", country: "Germany" },
  { slug: "copenhagen", name: "Copenhagen", type: "CITY", country: "Denmark" },
  { slug: "stockholm", name: "Stockholm", type: "CITY", country: "Sweden" },
  { slug: "norwegian-fjords", name: "Norwegian Fjords", type: "AREA", country: "Norway" },
  { slug: "finnish-lapland", name: "Finnish Lapland", type: "AREA", country: "Finland", aliases: "Northern Lights, aurora" },

  // Middle East / Africa
  { slug: "dubai", name: "Dubai", type: "CITY", country: "United Arab Emirates" },
  { slug: "abu-dhabi", name: "Abu Dhabi", type: "CITY", country: "United Arab Emirates" },
  { slug: "petra", name: "Petra / Wadi Rum", type: "AREA", country: "Jordan" },
  { slug: "jerusalem", name: "Jerusalem", type: "CITY", country: "Israel" },
  { slug: "cairo", name: "Cairo / Nile River", type: "AREA", country: "Egypt" },
  { slug: "marrakech", name: "Marrakech", type: "CITY", country: "Morocco" },
  { slug: "fes", name: "Fes", type: "CITY", country: "Morocco" },
  { slug: "cape-town", name: "Cape Town", type: "CITY", country: "South Africa" },
  { slug: "kruger", name: "Kruger National Park & safaris", type: "AREA", country: "South Africa", aliases: "Sabi Sand" },
  { slug: "botswana-safari", name: "Botswana (Okavango)", type: "AREA", country: "Botswana", aliases: "safari" },
  { slug: "serengeti", name: "Serengeti & Tanzania safari", type: "AREA", country: "Tanzania", aliases: "Ngorongoro" },
  { slug: "zanzibar", name: "Zanzibar", type: "CITY", country: "Tanzania" },
  { slug: "masai-mara", name: "Masai Mara", type: "AREA", country: "Kenya" },
  { slug: "seychelles", name: "Seychelles", type: "COUNTRY", country: "Seychelles" },
  { slug: "mauritius", name: "Mauritius", type: "COUNTRY", country: "Mauritius" },

  // Asia / Pacific
  { slug: "tokyo", name: "Tokyo", type: "CITY", country: "Japan" },
  { slug: "kyoto", name: "Kyoto", type: "CITY", country: "Japan" },
  { slug: "osaka", name: "Osaka", type: "CITY", country: "Japan" },
  { slug: "hokkaido", name: "Hokkaido", type: "AREA", country: "Japan", aliases: "Niseko" },
  { slug: "seoul", name: "Seoul", type: "CITY", country: "South Korea" },
  { slug: "beijing", name: "Beijing", type: "CITY", country: "China" },
  { slug: "shanghai", name: "Shanghai", type: "CITY", country: "China" },
  { slug: "hong-kong", name: "Hong Kong", type: "CITY", country: "Hong Kong" },
  { slug: "taipei", name: "Taipei", type: "CITY", country: "Taiwan" },
  { slug: "singapore-city", name: "Singapore", type: "CITY", country: "Singapore" },
  { slug: "bangkok", name: "Bangkok", type: "CITY", country: "Thailand" },
  { slug: "phuket", name: "Phuket & Phi Phi", type: "CITY", country: "Thailand" },
  { slug: "chiang-mai", name: "Chiang Mai", type: "CITY", country: "Thailand" },
  { slug: "koh-samui", name: "Koh Samui", type: "CITY", country: "Thailand" },
  { slug: "hanoi", name: "Hanoi & Halong Bay", type: "AREA", country: "Vietnam" },
  { slug: "ho-chi-minh", name: "Ho Chi Minh City", type: "CITY", country: "Vietnam", aliases: "Saigon" },
  { slug: "bali", name: "Bali", type: "CITY", country: "Indonesia", aliases: "Ubud, Seminyak" },
  { slug: "maldives", name: "Maldives", type: "COUNTRY", country: "Maldives" },
  { slug: "sri-lanka", name: "Sri Lanka", type: "COUNTRY", country: "Sri Lanka" },
  { slug: "rajasthan", name: "Rajasthan (Jaipur, Udaipur, Jodhpur)", type: "AREA", country: "India" },
  { slug: "kerala", name: "Kerala", type: "AREA", country: "India" },
  { slug: "sydney", name: "Sydney", type: "CITY", country: "Australia" },
  { slug: "great-barrier-reef", name: "Great Barrier Reef", type: "AREA", country: "Australia" },
  { slug: "melbourne", name: "Melbourne", type: "CITY", country: "Australia" },
  { slug: "outback", name: "Australian Outback (Uluru)", type: "AREA", country: "Australia" },
  { slug: "auckland", name: "Auckland", type: "CITY", country: "New Zealand" },
  { slug: "queenstown", name: "Queenstown", type: "CITY", country: "New Zealand" },
  { slug: "bora-bora", name: "Bora Bora", type: "CITY", country: "French Polynesia" },
  { slug: "moorea", name: "Mo'orea", type: "CITY", country: "French Polynesia" },

  // South America
  { slug: "rio-de-janeiro", name: "Rio de Janeiro", type: "CITY", country: "Brazil" },
  { slug: "sao-paulo", name: "São Paulo", type: "CITY", country: "Brazil" },
  { slug: "iguazu", name: "Iguazu Falls", type: "AREA", country: "Brazil" },
  { slug: "buenos-aires", name: "Buenos Aires", type: "CITY", country: "Argentina" },
  { slug: "patagonia", name: "Patagonia", type: "AREA", country: "Argentina" },
  { slug: "machu-picchu", name: "Machu Picchu / Cusco / Sacred Valley", type: "AREA", country: "Peru" },
  { slug: "galapagos", name: "Galápagos Islands", type: "AREA", country: "Ecuador" },
  { slug: "cartagena", name: "Cartagena", type: "CITY", country: "Colombia" },
  { slug: "atacama", name: "Atacama Desert", type: "AREA", country: "Chile" },
  { slug: "antarctica", name: "Antarctica", type: "AREA" },
];
